# Generated by Django 5.2 on 2025-04-22 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='followed_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='restapi.user'),
        ),
        migrations.AlterField(
            model_name='follows',
            name='following_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='restapi.user'),
        ),
    ]
